const optoutlinks = [
  {"Name":"doubleclick.net",
  "Link":"https://googleads.g.doubleclick.net/ads/preferences"},
  {"Name":"Google.com",
  "Link":"https://www.google.com/ads/preferences/?hl=en_US"},
  {"Name":"adnxs.com",
  "Link":"https://www.appnexus.com/platform-privacy-policy#choices"},
  {"Name":"quantserve.com",
  "Link":"https://www.quantcast.com/opt-out/"},
  {"Name":"rubiconproject.com",
  "Link":"https://rubiconproject.com/privacy/consumer-online-profile-and-opt-out/"},
  {"Name":"facebook.com",
  "Link":"https://www.facebook.com/privacy/explanation"},
  {"Name":"criteo.com",
  "Link":"https://www.criteo.com/privacy/disable-criteo-services-on-internet-browsers/"},
  {"Name":"twitter.com",
  "Link":"https://twitter.com/settings/security"},
  {"Name":"bing.com",
  "Link":"https://ssl.bing.com/profile/history?oma=toggle_off"},
  {"Name":"youtube.com",
  "Link":"https://www.youtube.com/feed/history"},
  {"Name":"amazon.com",
  "Link":"https://www.amazon.com/adprefs/"},
  {"Name":"amazon-adsystem",
  "Link":"https://www.amazon.com/adprefs/"},
  {"Name":"linkedin.com",
  "Link":"https://www.linkedin.com/psettings/advertising-data"},
  {"Name":"googleads.g.doubleclick.net",
  "Link":"https://googleads.g.doubleclick.net/ads/preferences"},
  {"Name":"foxnews.com",
  "Link":"https://www.foxnews.com/donotsell"},
  {"Name":"google-analytics.com",
  "Link":"https://policies.google.com/privacy"},
  {"Name":"gumgum.com",
  "Link":"https://privacyportal.onetrust.com/webform/fbe4d6b4-7f02-4251-bc4b-142d5109ae3e/1683277a-0ae1-47dd-8845-5e811a07e307"},
  {"Name":"stripe.com",
  "Link":"https://stripe.com/privacy"},
  {"Name":"yahoo.com",
  "Link":"https://stripe.com/privacy"}


];

export default optoutlinks;
